### ISSUE TITLE
Windows 10 native style

### ISSUE THREAD

**Issue by matkuki** [nim-lang/ui#17]
Currently on Windows 10 the controls in the examples have the `Classic (Windows XP)` style.
This is how the `controlgallery2` example looks currently:
![image](https://user-images.githubusercontent.com/10289651/41024896-be384186-6970-11e8-9e81-7641758b691d.png)

Is there a way to change this to the native Windows 10 style?

**Comment by Araq** [comment]
Good question. I don't know. :-)

**Comment by data-man** [comment]
For this feature ```libui.manifest``` should be updated.

**Comment by matkuki** [comment]
The above example was compiled with MinGW-w64, but compiling it with MSVC gives:
![image](https://user-images.githubusercontent.com/10289651/41061058-ba629b54-69d1-11e8-854f-55b5d30a4a0a.png)
If there is a way to do the same with MinGW, please let me know.

**Comment by veksha** [comment]
@matkuki , look how it's done here: https://github.com/khchen/winim/blob/master/winim/inc/winimbase.nim
"winim32.res" or "winim64.res" is linked for MinGW compilation.

easy way:
1. `nimble install winim`
2. add `import winim` to your code (this will link automatically either winim32.res or winim64.res)

advanced way: copy these files to your project folder and add `{.link: "winim32.res".}` to your code. (or winim64.res for 64 bit)
