### ISSUE TITLE
Do you have a plan for libui alpha 4?

### ISSUE THREAD

**Issue by ba0f3** [nim-lang/ui#20]
I need new `uiTable` badly

**Comment by dom96** [comment]
Wrap it and make a PR :)

**Comment by ba0f3** [comment]
there are a lots of changes, and `c2nim` is not working as exptected

**Comment by ba0f3** [comment]
@dom96 I need help
Im working on a high-level binding for  `uiTable`, but I got error on this line https://github.com/ba0f3/ui/blob/wip/ui.nim#L533

I tried some workarounds but unable to pass a callback into this proc

**Comment by teras** [comment]
Hello, is there any progress on this issue?
It sounds like a very interesting aspect to be able to use tables with nim/libui right now. 🙂

**Comment by Araq** [comment]
This has been implemented, thanks to @ba0f3
