### ISSUE TITLE
Cross-compiling on Linux for Windows gives two linker errors

### ISSUE THREAD

**Issue by apahl** [nim-lang/ui#9]
Araq, compiling on Linux for Linux now works, this is awesome!!

Should cross-compiling to Windows also work?
Because, when I cross-compile on Linux for Windows using this line:  
`nim --os:windows --cpu:amd64 --gcc.exe:x86_64-w64-mingw32-gcc --gcc.linkerexe:x86_64-w64-mingw32-gcc --app:gui c controllgallery2.nim`

I get this linking error:
```
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lUxTheme
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lUsp10
```

Do you have an idea how to resolve this?

Also, there is this error complaining about the backslashes in the path to `resources.o` when cross-compiling on Linux (I have changed them to forward slashes for now).

Many thanks for your help again, this is really highly appreciated.

Kind regards,  
Axel

**Comment by Araq** [comment]
I'm using the mingw64 from here: 

```
https://nim-lang.org/download/mingw64-6.3.0.7z
``` 

It contains the libraries in ``mingw64\x86_64-w64-mingw32\lib``.

> Also, there is this error complaining about the backslashes in the path to resources.o when cross-compiling on Linux (I have changed them to forward slashes for now).

Sure we can fix that, but I would look into a Wine environment to do the cross compilations. This way native Windows paths are not an issue and you can test the resulting programs too.

**Comment by apahl** [comment]
The names of the two libraries to link against have to be lower-case (`uxtheme` and `usp10`), then they are also found by Linux mingw64 (Linux is case-sensitive... ;-)).

But now I get a massive list of different errors:
```
Hint:  [Link]
/home/pahl/dev/nim/libui/ex1/nimcache/win_alloc.cpp.obj:alloc.cpp:(.text+0x25): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)'
/home/pahl/dev/nim/libui/ex1/nimcache/win_alloc.cpp.obj:alloc.cpp:(.text+0x31): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
/home/pahl/dev/nim/libui/ex1/nimcache/win_alloc.cpp.obj:alloc.cpp:(.text+0xe3): undefined reference to `std::ostream::operator<<(void const*)'
/home/pahl/dev/nim/libui/ex1/nimcache/win_alloc.cpp.obj:alloc.cpp:(.text+0xf2): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/home/pahl/dev/nim/libui/ex1/nimcache/win_alloc.cpp.obj:alloc.cpp:(.text+0xfd): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
[... plus many more...]
```

Stuck again...

**Comment by Araq** [comment]
> But now I get a massive list of different errors:

That reads like the C++ library was not linked. Use ``nim cpp``  instead of ``nim c``?

**Comment by apahl** [comment]
No, that does not work, either.  
Well, I had some success cross-compiling iup apps to Windows, so I will use that for now.

Thanks a lot for your efforts, again, Araq, Nim is a really great project!!

**Comment by Araq** [comment]
Well now I'm curious. Why not use ``Wine`` to cross-compile?

**Comment by apahl** [comment]
There are no really strong reasons and I might try it at some time:  
* I would prefer to only use one environment (my native Linux) to develop for Linux and Windows
* Supporting cross-compilation is one of Nim's strongest suits, imo
* Using Wine is not really cross-compiling
* When I use Wine I have to maintain another version of Nim on my machine
* I wanted to try out iup on Nim anyway

**Comment by R030t1** [comment]
I'm getting this error as well. Is the recommended solution really to download a prebuilt toolchain? For my usecase that isn't acceptable.

**Comment by deroLub6** [comment]
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lboost_program_options-mt
collect2: error: ld returned 1 exit status
please help me to solve this error
